# Приведение к шкале от 0 до 1

In [2]:
import os
os.chdir('C:/Users/User/Desktop/homework/Аналитический маркетинг/')

In [3]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler

In [45]:
filename = 'git/data/pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)
dataframe.head(10)

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1
5     5   116    74     0     0  25.6  0.201   30      0
6     3    78    50    32    88  31.0  0.248   26      1
7    10   115     0     0     0  35.3  0.134   29      0
8     2   197    70    45   543  30.5  0.158   53      1
9     8   125    96     0     0   0.0  0.232   54      1

In [6]:
array = dataframe.values

In [7]:
X = array[:,0:8]
Y = array[:,8]

In [9]:
scaler = MinMaxScaler(feature_range = (0,1))
rescaledX = scaler.fit_transform(X)

In [10]:
set_printoptions(precision = 3)

In [11]:
rescaledX[:5]

array([[0.353, 0.744, 0.59 , 0.354, 0.   , 0.501, 0.234, 0.483],
       [0.059, 0.427, 0.541, 0.293, 0.   , 0.396, 0.117, 0.167],
       [0.471, 0.92 , 0.525, 0.   , 0.   , 0.347, 0.254, 0.183],
       [0.059, 0.447, 0.541, 0.232, 0.111, 0.419, 0.038, 0.   ],
       [0.   , 0.688, 0.328, 0.354, 0.199, 0.642, 0.944, 0.2  ]])

# Стандартизация данных

In [12]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)

In [15]:
print(rescaledX[0:5,:])

[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0.766  1.41   5.485 -0.02 ]]


# Нормализация

In [16]:
from sklearn.preprocessing import Normalizer

In [17]:
scaler = Normalizer().fit(X)
normalizedX = scaler.transform(X)

In [18]:
normalizedX[0:5,:]

array([[0.034, 0.828, 0.403, 0.196, 0.   , 0.188, 0.004, 0.28 ],
       [0.008, 0.716, 0.556, 0.244, 0.   , 0.224, 0.003, 0.261],
       [0.04 , 0.924, 0.323, 0.   , 0.   , 0.118, 0.003, 0.162],
       [0.007, 0.588, 0.436, 0.152, 0.622, 0.186, 0.001, 0.139],
       [0.   , 0.596, 0.174, 0.152, 0.731, 0.188, 0.01 , 0.144]])

# Бинаризация данных

In [19]:
from sklearn.preprocessing import Binarizer

In [20]:
binarizer = Binarizer(threshold = 0.0).fit(X)
binaryX = binarizer.transform(X)

In [21]:
binaryX[0:5,:]

array([[1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 0., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1.]])

# Отбор признаков

In [ ]:
# по одному добавляем значимые признаки

In [22]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

In [23]:
test = SelectKBest(score_func=f_classif, k=4)
fit = test.fit(X, Y)

In [24]:
fit.scores_

array([ 39.67 , 213.162,   3.257,   4.304,  13.281,  71.772,  23.871,
        46.141])

In [26]:
features = fit.transform(X)
features[0:5,:]

array([[  6. , 148. ,  33.6,  50. ],
       [  1. ,  85. ,  26.6,  31. ],
       [  8. , 183. ,  23.3,  32. ],
       [  1. ,  89. ,  28.1,  21. ],
       [  0. , 137. ,  43.1,  33. ]])

In [ ]:
# по одному убираем незначимые признаки (RFE)

In [27]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [28]:
model = LogisticRegression(solver = 'liblinear')

In [30]:
rfe = RFE(model, 3)
fit = rfe.fit(X,Y)

In [32]:
print('Количество признаков: %d' %fit.n_features_)

Количество признаков: 3


In [34]:
print('Отобранные признаки: %s' %fit.support_)

Отобранные признаки: [ True False False False False  True  True False]


In [35]:
print('Ранжирование признаков: %s' %fit.ranking_)

Ранжирование признаков: [1 2 3 5 6 1 1 4]


# Анализ главных компонент (PCA)

In [36]:
from sklearn.decomposition import PCA

In [38]:
pca = PCA(n_components = 3)
fit = pca.fit(X)

In [39]:
print('Объясненная дисперсия: %s' %fit.explained_variance_ratio_)

Объясненная дисперсия: [0.889 0.062 0.026]


In [40]:
fit.components_

array([[-2.022e-03,  9.781e-02,  1.609e-02,  6.076e-02,  9.931e-01,
         1.401e-02,  5.372e-04, -3.565e-03],
       [-2.265e-02, -9.722e-01, -1.419e-01,  5.786e-02,  9.463e-02,
        -4.697e-02, -8.168e-04, -1.402e-01],
       [-2.246e-02,  1.434e-01, -9.225e-01, -3.070e-01,  2.098e-02,
        -1.324e-01, -6.400e-04, -1.255e-01]])

по методу Джинни отбор признаков

In [41]:
from sklearn.ensemble import ExtraTreesClassifier

In [43]:
model = ExtraTreesClassifier(n_estimators = 100)
model.fit(X,Y)

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
                     max_depth=None, max_features='auto', max_leaf_nodes=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100,
                     n_jobs=None, oob_score=False, random_state=None, verbose=0,
                     warm_start=False)

In [44]:
model.feature_importances_

array([0.107, 0.232, 0.101, 0.078, 0.074, 0.142, 0.118, 0.148])